name: Package Application with Pyinstaller
# https://github.com/marketplace/actions/python-build-for-windows-pyinstaller
on:
  push:
    branches: [ main, cole ]
  pull_request:
    branches: [ main, cole ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: vednig/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows
